package com.my.rpc.testMessage;

messageBlock MessageBeerArray
{
	message BeerSort
	{
		seq<string> names;
	};
	
	message Beer
	{
		string Brand;
	    BeerSort Sort;
		float Alcohol;
	    string Brewery;
	};
	
	message BeerArray
	{
		seq<Beer> beers;
	};
	
	message BeerMap
	{
		map<string, BeerArray> beers;
	};
};

interface IBeerQuery
{
	BeerArray queryBeers(float param1, string param2, RPCCommonMessage.SeqString param3, RPCCommonMessage.MapStrInt param4, binary param5, RPCCommonMessage.SeqInt param6) = 1;
	void      voidReturnTest(int param1) = 2;
	void      exceptionTest() = 3;
};