/*
 * Automatically generated by jrpcgen 1.0.7 on 19-1-6 ионГ10:33
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "msg" ONC/RPC program.
 */
public interface msg {
    public static final int sendmsgEx_2 = 2;
    public static final int msgservExtend = 1234568;
    public static final int msgserv = 1234567;
    public static final int sendmsg_2 = 1;
    public static final int MSGSERV_V2 = 2;
    public static final int sendmsg_1 = 2;
    public static final int MSGSERV_V1 = 1;
}
// End of msg.java
