/*
 * Automatically generated by jrpcgen 1.0.7 on 19-1-6 ÉÏÎç10:33
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class msg_msgservExtend_ServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public msg_msgservExtend_ServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public msg_msgservExtend_ServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public msg_msgservExtend_ServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(msg.msgservExtend, 2),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 2 ) {
            switch ( procedure ) {
            case 1: {
                XdrString args$ = new XdrString();
                call.retrieveCall(args$);
                XdrString result$ = new XdrString(sendmsg_2(args$.stringValue()));
                call.reply(result$);
                break;
            }
            case 2: {
                XdrString args$ = new XdrString();
                call.retrieveCall(args$);
                XdrString result$ = new XdrString(sendmsgEx_2(args$.stringValue()));
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract String sendmsg_2(String arg1);

    public abstract String sendmsgEx_2(String arg1);

}
// End of msg_msgservExtend_ServerStub.java
