// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BeerArray.proto

package com.learningjava.serializationPerformance.tester;

public final class BeerArrayProtos {
  private BeerArrayProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BeerSortOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.BeerSort)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string names = 1;</code>
     */
    java.util.List<java.lang.String>
        getNamesList();
    /**
     * <code>repeated string names = 1;</code>
     */
    int getNamesCount();
    /**
     * <code>repeated string names = 1;</code>
     */
    java.lang.String getNames(int index);
    /**
     * <code>repeated string names = 1;</code>
     */
    com.google.protobuf.ByteString
        getNamesBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.BeerSort}
   */
  public  static final class BeerSort extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.BeerSort)
      BeerSortOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BeerSort.newBuilder() to construct.
    private BeerSort(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BeerSort() {
      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BeerSort(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                names_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              names_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          names_ = names_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerSort_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerSort_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.class, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder.class);
    }

    public static final int NAMES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList names_;
    /**
     * <code>repeated string names = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNamesList() {
      return names_;
    }
    /**
     * <code>repeated string names = 1;</code>
     */
    public int getNamesCount() {
      return names_.size();
    }
    /**
     * <code>repeated string names = 1;</code>
     */
    public java.lang.String getNames(int index) {
      return names_.get(index);
    }
    /**
     * <code>repeated string names = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNamesBytes(int index) {
      return names_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < names_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, names_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < names_.size(); i++) {
          dataSize += computeStringSizeNoTag(names_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort)) {
        return super.equals(obj);
      }
      com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort other = (com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort) obj;

      boolean result = true;
      result = result && getNamesList()
          .equals(other.getNamesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNamesCount() > 0) {
        hash = (37 * hash) + NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.BeerSort}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.BeerSort)
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerSort_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerSort_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.class, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder.class);
      }

      // Construct using com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerSort_descriptor;
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort getDefaultInstanceForType() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance();
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort build() {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort buildPartial() {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort result = new com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          names_ = names_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.names_ = names_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort) {
          return mergeFrom((com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort other) {
        if (other == com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance()) return this;
        if (!other.names_.isEmpty()) {
          if (names_.isEmpty()) {
            names_ = other.names_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNamesIsMutable();
            names_.addAll(other.names_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          names_ = new com.google.protobuf.LazyStringArrayList(names_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNamesList() {
        return names_.getUnmodifiableView();
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public int getNamesCount() {
        return names_.size();
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public java.lang.String getNames(int index) {
        return names_.get(index);
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNamesBytes(int index) {
        return names_.getByteString(index);
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public Builder setNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public Builder addNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public Builder addAllNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, names_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public Builder clearNames() {
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 1;</code>
       */
      public Builder addNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.BeerSort)
    }

    // @@protoc_insertion_point(class_scope:tutorial.BeerSort)
    private static final com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort();
    }

    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BeerSort>
        PARSER = new com.google.protobuf.AbstractParser<BeerSort>() {
      @java.lang.Override
      public BeerSort parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeerSort(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BeerSort> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BeerSort> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Beer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Brand = 1;</code>
     */
    boolean hasBrand();
    /**
     * <code>required string Brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>required string Brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>required .tutorial.BeerSort Sort = 2;</code>
     */
    boolean hasSort();
    /**
     * <code>required .tutorial.BeerSort Sort = 2;</code>
     */
    com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort getSort();
    /**
     * <code>required .tutorial.BeerSort Sort = 2;</code>
     */
    com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder getSortOrBuilder();

    /**
     * <code>required float Alcohol = 3;</code>
     */
    boolean hasAlcohol();
    /**
     * <code>required float Alcohol = 3;</code>
     */
    float getAlcohol();

    /**
     * <code>required string Brewery = 4;</code>
     */
    boolean hasBrewery();
    /**
     * <code>required string Brewery = 4;</code>
     */
    java.lang.String getBrewery();
    /**
     * <code>required string Brewery = 4;</code>
     */
    com.google.protobuf.ByteString
        getBreweryBytes();
  }
  /**
   * Protobuf type {@code tutorial.Beer}
   */
  public  static final class Beer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Beer)
      BeerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Beer.newBuilder() to construct.
    private Beer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Beer() {
      brand_ = "";
      alcohol_ = 0F;
      brewery_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Beer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              brand_ = bs;
              break;
            }
            case 18: {
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = sort_.toBuilder();
              }
              sort_ = input.readMessage(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sort_);
                sort_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              alcohol_ = input.readFloat();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              brewery_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_Beer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_Beer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.class, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder.class);
    }

    private int bitField0_;
    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object brand_;
    /**
     * <code>required string Brand = 1;</code>
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SORT_FIELD_NUMBER = 2;
    private com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort sort_;
    /**
     * <code>required .tutorial.BeerSort Sort = 2;</code>
     */
    public boolean hasSort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tutorial.BeerSort Sort = 2;</code>
     */
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort getSort() {
      return sort_ == null ? com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance() : sort_;
    }
    /**
     * <code>required .tutorial.BeerSort Sort = 2;</code>
     */
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder getSortOrBuilder() {
      return sort_ == null ? com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance() : sort_;
    }

    public static final int ALCOHOL_FIELD_NUMBER = 3;
    private float alcohol_;
    /**
     * <code>required float Alcohol = 3;</code>
     */
    public boolean hasAlcohol() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float Alcohol = 3;</code>
     */
    public float getAlcohol() {
      return alcohol_;
    }

    public static final int BREWERY_FIELD_NUMBER = 4;
    private volatile java.lang.Object brewery_;
    /**
     * <code>required string Brewery = 4;</code>
     */
    public boolean hasBrewery() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string Brewery = 4;</code>
     */
    public java.lang.String getBrewery() {
      java.lang.Object ref = brewery_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brewery_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Brewery = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBreweryBytes() {
      java.lang.Object ref = brewery_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brewery_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlcohol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBrewery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getSort());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, alcohol_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, brewery_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSort());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, alcohol_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, brewery_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer)) {
        return super.equals(obj);
      }
      com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer other = (com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer) obj;

      boolean result = true;
      result = result && (hasBrand() == other.hasBrand());
      if (hasBrand()) {
        result = result && getBrand()
            .equals(other.getBrand());
      }
      result = result && (hasSort() == other.hasSort());
      if (hasSort()) {
        result = result && getSort()
            .equals(other.getSort());
      }
      result = result && (hasAlcohol() == other.hasAlcohol());
      if (hasAlcohol()) {
        result = result && (
            java.lang.Float.floatToIntBits(getAlcohol())
            == java.lang.Float.floatToIntBits(
                other.getAlcohol()));
      }
      result = result && (hasBrewery() == other.hasBrewery());
      if (hasBrewery()) {
        result = result && getBrewery()
            .equals(other.getBrewery());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBrand()) {
        hash = (37 * hash) + BRAND_FIELD_NUMBER;
        hash = (53 * hash) + getBrand().hashCode();
      }
      if (hasSort()) {
        hash = (37 * hash) + SORT_FIELD_NUMBER;
        hash = (53 * hash) + getSort().hashCode();
      }
      if (hasAlcohol()) {
        hash = (37 * hash) + ALCOHOL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getAlcohol());
      }
      if (hasBrewery()) {
        hash = (37 * hash) + BREWERY_FIELD_NUMBER;
        hash = (53 * hash) + getBrewery().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Beer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Beer)
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_Beer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_Beer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.class, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder.class);
      }

      // Construct using com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSortFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (sortBuilder_ == null) {
          sort_ = null;
        } else {
          sortBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        alcohol_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        brewery_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_Beer_descriptor;
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer getDefaultInstanceForType() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.getDefaultInstance();
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer build() {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer buildPartial() {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer result = new com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (sortBuilder_ == null) {
          result.sort_ = sort_;
        } else {
          result.sort_ = sortBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.alcohol_ = alcohol_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.brewery_ = brewery_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer) {
          return mergeFrom((com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer other) {
        if (other == com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          bitField0_ |= 0x00000001;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasSort()) {
          mergeSort(other.getSort());
        }
        if (other.hasAlcohol()) {
          setAlcohol(other.getAlcohol());
        }
        if (other.hasBrewery()) {
          bitField0_ |= 0x00000008;
          brewery_ = other.brewery_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasBrand()) {
          return false;
        }
        if (!hasSort()) {
          return false;
        }
        if (!hasAlcohol()) {
          return false;
        }
        if (!hasBrewery()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object brand_ = "";
      /**
       * <code>required string Brand = 1;</code>
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Brand = 1;</code>
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string Brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }

      private com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort sort_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder> sortBuilder_;
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public boolean hasSort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort getSort() {
        if (sortBuilder_ == null) {
          return sort_ == null ? com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance() : sort_;
        } else {
          return sortBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public Builder setSort(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort value) {
        if (sortBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sort_ = value;
          onChanged();
        } else {
          sortBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public Builder setSort(
          com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder builderForValue) {
        if (sortBuilder_ == null) {
          sort_ = builderForValue.build();
          onChanged();
        } else {
          sortBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public Builder mergeSort(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort value) {
        if (sortBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              sort_ != null &&
              sort_ != com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance()) {
            sort_ =
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.newBuilder(sort_).mergeFrom(value).buildPartial();
          } else {
            sort_ = value;
          }
          onChanged();
        } else {
          sortBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public Builder clearSort() {
        if (sortBuilder_ == null) {
          sort_ = null;
          onChanged();
        } else {
          sortBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder getSortBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSortFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder getSortOrBuilder() {
        if (sortBuilder_ != null) {
          return sortBuilder_.getMessageOrBuilder();
        } else {
          return sort_ == null ?
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.getDefaultInstance() : sort_;
        }
      }
      /**
       * <code>required .tutorial.BeerSort Sort = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder> 
          getSortFieldBuilder() {
        if (sortBuilder_ == null) {
          sortBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSort.Builder, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerSortOrBuilder>(
                  getSort(),
                  getParentForChildren(),
                  isClean());
          sort_ = null;
        }
        return sortBuilder_;
      }

      private float alcohol_ ;
      /**
       * <code>required float Alcohol = 3;</code>
       */
      public boolean hasAlcohol() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float Alcohol = 3;</code>
       */
      public float getAlcohol() {
        return alcohol_;
      }
      /**
       * <code>required float Alcohol = 3;</code>
       */
      public Builder setAlcohol(float value) {
        bitField0_ |= 0x00000004;
        alcohol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float Alcohol = 3;</code>
       */
      public Builder clearAlcohol() {
        bitField0_ = (bitField0_ & ~0x00000004);
        alcohol_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object brewery_ = "";
      /**
       * <code>required string Brewery = 4;</code>
       */
      public boolean hasBrewery() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string Brewery = 4;</code>
       */
      public java.lang.String getBrewery() {
        java.lang.Object ref = brewery_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brewery_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Brewery = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBreweryBytes() {
        java.lang.Object ref = brewery_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brewery_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Brewery = 4;</code>
       */
      public Builder setBrewery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        brewery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Brewery = 4;</code>
       */
      public Builder clearBrewery() {
        bitField0_ = (bitField0_ & ~0x00000008);
        brewery_ = getDefaultInstance().getBrewery();
        onChanged();
        return this;
      }
      /**
       * <code>required string Brewery = 4;</code>
       */
      public Builder setBreweryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        brewery_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Beer)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Beer)
    private static final com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer();
    }

    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Beer>
        PARSER = new com.google.protobuf.AbstractParser<Beer>() {
      @java.lang.Override
      public Beer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Beer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Beer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Beer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BeerArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.BeerArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    java.util.List<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer> 
        getBeersList();
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer getBeers(int index);
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    int getBeersCount();
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    java.util.List<? extends com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder> 
        getBeersOrBuilderList();
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder getBeersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.BeerArray}
   */
  public  static final class BeerArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.BeerArray)
      BeerArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BeerArray.newBuilder() to construct.
    private BeerArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BeerArray() {
      beers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BeerArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                beers_ = new java.util.ArrayList<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer>();
                mutable_bitField0_ |= 0x00000001;
              }
              beers_.add(
                  input.readMessage(com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          beers_ = java.util.Collections.unmodifiableList(beers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.class, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.Builder.class);
    }

    public static final int BEERS_FIELD_NUMBER = 1;
    private java.util.List<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer> beers_;
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    public java.util.List<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer> getBeersList() {
      return beers_;
    }
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    public java.util.List<? extends com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder> 
        getBeersOrBuilderList() {
      return beers_;
    }
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    public int getBeersCount() {
      return beers_.size();
    }
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer getBeers(int index) {
      return beers_.get(index);
    }
    /**
     * <code>repeated .tutorial.Beer beers = 1;</code>
     */
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder getBeersOrBuilder(
        int index) {
      return beers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getBeersCount(); i++) {
        if (!getBeers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < beers_.size(); i++) {
        output.writeMessage(1, beers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < beers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, beers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray)) {
        return super.equals(obj);
      }
      com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray other = (com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray) obj;

      boolean result = true;
      result = result && getBeersList()
          .equals(other.getBeersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBeersCount() > 0) {
        hash = (37 * hash) + BEERS_FIELD_NUMBER;
        hash = (53 * hash) + getBeersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.BeerArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.BeerArray)
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.class, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.Builder.class);
      }

      // Construct using com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBeersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (beersBuilder_ == null) {
          beers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          beersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.internal_static_tutorial_BeerArray_descriptor;
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray getDefaultInstanceForType() {
        return com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.getDefaultInstance();
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray build() {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray buildPartial() {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray result = new com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray(this);
        int from_bitField0_ = bitField0_;
        if (beersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            beers_ = java.util.Collections.unmodifiableList(beers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.beers_ = beers_;
        } else {
          result.beers_ = beersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray) {
          return mergeFrom((com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray other) {
        if (other == com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray.getDefaultInstance()) return this;
        if (beersBuilder_ == null) {
          if (!other.beers_.isEmpty()) {
            if (beers_.isEmpty()) {
              beers_ = other.beers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBeersIsMutable();
              beers_.addAll(other.beers_);
            }
            onChanged();
          }
        } else {
          if (!other.beers_.isEmpty()) {
            if (beersBuilder_.isEmpty()) {
              beersBuilder_.dispose();
              beersBuilder_ = null;
              beers_ = other.beers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              beersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBeersFieldBuilder() : null;
            } else {
              beersBuilder_.addAllMessages(other.beers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getBeersCount(); i++) {
          if (!getBeers(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer> beers_ =
        java.util.Collections.emptyList();
      private void ensureBeersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          beers_ = new java.util.ArrayList<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer>(beers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder> beersBuilder_;

      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public java.util.List<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer> getBeersList() {
        if (beersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(beers_);
        } else {
          return beersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public int getBeersCount() {
        if (beersBuilder_ == null) {
          return beers_.size();
        } else {
          return beersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer getBeers(int index) {
        if (beersBuilder_ == null) {
          return beers_.get(index);
        } else {
          return beersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder setBeers(
          int index, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer value) {
        if (beersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeersIsMutable();
          beers_.set(index, value);
          onChanged();
        } else {
          beersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder setBeers(
          int index, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder builderForValue) {
        if (beersBuilder_ == null) {
          ensureBeersIsMutable();
          beers_.set(index, builderForValue.build());
          onChanged();
        } else {
          beersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder addBeers(com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer value) {
        if (beersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeersIsMutable();
          beers_.add(value);
          onChanged();
        } else {
          beersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder addBeers(
          int index, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer value) {
        if (beersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeersIsMutable();
          beers_.add(index, value);
          onChanged();
        } else {
          beersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder addBeers(
          com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder builderForValue) {
        if (beersBuilder_ == null) {
          ensureBeersIsMutable();
          beers_.add(builderForValue.build());
          onChanged();
        } else {
          beersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder addBeers(
          int index, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder builderForValue) {
        if (beersBuilder_ == null) {
          ensureBeersIsMutable();
          beers_.add(index, builderForValue.build());
          onChanged();
        } else {
          beersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder addAllBeers(
          java.lang.Iterable<? extends com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer> values) {
        if (beersBuilder_ == null) {
          ensureBeersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, beers_);
          onChanged();
        } else {
          beersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder clearBeers() {
        if (beersBuilder_ == null) {
          beers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          beersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public Builder removeBeers(int index) {
        if (beersBuilder_ == null) {
          ensureBeersIsMutable();
          beers_.remove(index);
          onChanged();
        } else {
          beersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder getBeersBuilder(
          int index) {
        return getBeersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder getBeersOrBuilder(
          int index) {
        if (beersBuilder_ == null) {
          return beers_.get(index);  } else {
          return beersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public java.util.List<? extends com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder> 
           getBeersOrBuilderList() {
        if (beersBuilder_ != null) {
          return beersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(beers_);
        }
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder addBeersBuilder() {
        return getBeersFieldBuilder().addBuilder(
            com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder addBeersBuilder(
          int index) {
        return getBeersFieldBuilder().addBuilder(
            index, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Beer beers = 1;</code>
       */
      public java.util.List<com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder> 
           getBeersBuilderList() {
        return getBeersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder> 
          getBeersFieldBuilder() {
        if (beersBuilder_ == null) {
          beersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer, com.learningjava.serializationPerformance.tester.BeerArrayProtos.Beer.Builder, com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerOrBuilder>(
                  beers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          beers_ = null;
        }
        return beersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.BeerArray)
    }

    // @@protoc_insertion_point(class_scope:tutorial.BeerArray)
    private static final com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray();
    }

    public static com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BeerArray>
        PARSER = new com.google.protobuf.AbstractParser<BeerArray>() {
      @java.lang.Override
      public BeerArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeerArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BeerArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BeerArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.learningjava.serializationPerformance.tester.BeerArrayProtos.BeerArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_BeerSort_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_BeerSort_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Beer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Beer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_BeerArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_BeerArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BeerArray.proto\022\010tutorial\"\031\n\010BeerSort\022" +
      "\r\n\005names\030\001 \003(\t\"Y\n\004Beer\022\r\n\005Brand\030\001 \002(\t\022 \n" +
      "\004Sort\030\002 \002(\0132\022.tutorial.BeerSort\022\017\n\007Alcoh" +
      "ol\030\003 \002(\002\022\017\n\007Brewery\030\004 \002(\t\"*\n\tBeerArray\022\035" +
      "\n\005beers\030\001 \003(\0132\016.tutorial.BeerBC\n0com.lea" +
      "rningjava.serializationPerformance.teste" +
      "rB\017BeerArrayProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_BeerSort_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_BeerSort_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_BeerSort_descriptor,
        new java.lang.String[] { "Names", });
    internal_static_tutorial_Beer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Beer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Beer_descriptor,
        new java.lang.String[] { "Brand", "Sort", "Alcohol", "Brewery", });
    internal_static_tutorial_BeerArray_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_BeerArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_BeerArray_descriptor,
        new java.lang.String[] { "Beers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
